version: "3.9"
services:
  tile-processor:
    container_name: TP_DEV
    image: python:latest
    working_dir: /workspaces/mbutil
    environment:
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/workspaces/
    volumes:
      - ../../nsi/compute-server/out:/workspaces/data
    command:
    - bash
    - -c
    - |
      cd /workspaces/
      git clone "https://github.com/mapbox/mbutil"
      bash
    tty: true

